webpage/Banger_box_project/src/Entity/Music.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MusicRepository")
 */
class Music
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $Date_added;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Author;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $base;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateAdded(): ?\DateTimeInterface
    {
        return $this->Date_added;
    }

    public function setDateAdded(\DateTimeInterface $Date_added): self
    {
        $this->Date_added = $Date_added;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->Author;
    }

    public function setAuthor(?string $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getBase(): ?string
    {
        return $this->base;
    }

    public function setBase(?string $base): self
    {
        $this->base = $base;

        return $this;
    }
}

webpage/Banger_box_project/src/Controller/MusicController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Music;

class MusicController extends AbstractController
{
    /**
     * @Route("/music", name="music")
     */
    public function music_view()
    {
		$repository = $this->getDoctrine()->getRepository(Music::class);
		$music_list = $repository->findAll();
		return $this->render('music\index.html.twig', array("music" => $music_list));
    }
}

webpage/Banger_box_project/templates/music/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}BngBxStdio{% endblock %}
{% block stylesheets %}{% endblock %}

{% block body %}

<table class="table table-dark">
<tr>
	<th>Title</th>
	<th>Year</th>
</tr>
{% for t in music %}
	<tr>
		<td>{{ t.title }}</td>
		<td>
		{% for m in t.author %}
    	{{ m }}
	<br>
		{% endfor %}
		</td>
		<td>{{ t.date_added }}</td>
	</tr>
{% endfor %}
</table>	

		

{% endblock %}

{% block javascripts %}{% endblock %}